services:
  web:
    container_name: web
    build:
      context: .
      target: build
    working_dir: /var/www/whatmovie
    volumes:
      - ./:/var/www/whatmovie
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/whatmovie/public
    ports:
      - "8080:80"
      - "5173:5173" # Vite
    depends_on:
      - db
    restart: always
    healthcheck: 
      test: "curl -s -I http://web/ | head -n 1 | grep '200 OK'"
      interval: 3s
      retries: 5
      start_period: 10s
  db:
    image: mariadb
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: whatmovie
      MYSQL_USER: whatmovie
      MYSQL_PASSWORD: password
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db-data:
