services:
  web:
    build: app
    depends_on:
      - db
    ports:
      - '${APP_PORT:-8080}:80'
    volumes:
      - ./app:/var/www/html/

  db:
    image: mariadb:latest
    ports:
      - '${DB_PORT:-3306}:3306'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${DB_NAME:-whatmovie}
      MYSQL_USER: ${DB_USER:-whatmovie}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}

volumes:
  db_data:
