date.timezone = Europe/Paris

; OPcache settings
opcache.enable = 0 ; Disable OPcache for development to reflect file changes immediately
opcache.enable_cli = 0
opcache.memory_consumption = 128
opcache.revalidate_freq = 0
opcache.validate_timestamps = 1 ; Ensure OPcache checks for file changes

apc.enable_cli = On

upload_max_filesize = 16M
post_max_size = 16M

realpath_cache_size = 4096k
realpath_cache_ttl = 7200

; Error reporting settings
display_errors = On
display_startup_errors = On
error_reporting = E_ALL

; Execution and memory limits
max_execution_time = 300
memory_limit = 512M

; Session settings
session.gc_maxlifetime = 1440
session.save_path = "/tmp"

; Xdebug settings
xdebug.mode = debug
xdebug.start_with_request = yes
xdebug.client_host = localhost
xdebug.client_port = 9003
xdebug.discover_client_host = true ; Automatically discover the client host for debugging
xdebug.profiler_enable_trigger = 1 ; Enable profiling trigger for performance analysis
